### ISSUE TITLE
Format of date uses comma instead of dot

### ISSUE THREAD

**Issue by eldraco** [verovaleros/webcrawler#5]
The format of the date is now
```
2023-12-29 23:43:49,493
```

Using a comma for the seconds instead of '.'

**Comment by verovaleros** [comment]
@eldraco I'm using asctime from logging, see https://docs.python.org/3/library/logging.html

```python
file_formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
```

What do you suggest instead?
